
include $(RTEMS_MAKEFILE_PATH)/Makefile.inc
include $(RTEMS_CUSTOM)
include $(RTEMS_ROOT)/make/leaf.cfg

INCLUDE=-I..
LIBS= ../libX11.a ../../microwin/src/obj/rtems_init.o ../../microwin/src/obj/FilesystemImage.o 

LDFLAGS+= -lnano-X -lt1 -lpng -lz -ljpeg -ltiff  -lm

all:
	$(CC) -o williams williams.c   rtems_main.c $(LIBS) $(LDFLAGS) $(CFLAGS) $(LDLIBS) 
	$(CC) -o queryfont queryfont.c rtems_main.c $(LIBS) $(LDFLAGS) $(CFLAGS) $(LDLIBS)
	$(CC) -o loadfont loadfont.c   rtems_main.c $(LIBS) $(LDFLAGS) $(CFLAGS) $(LDLIBS)
clean:
	rm williams
	rm queryfont
	rm loadfont
